services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: OpenQuizzerDataBase
      MYSQL_ROOT_PASSWORD: OpenQuizzerDB1703
    
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  back:
    build:
      context: Back
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: OpenQuizzerDB1703
      DB_NAME: OpenQuizzerDataBase
    depends_on:
      - database
    #develop:
    #  watch:
    #    - action: rebuild
    #      path: ./Back/.
  front:
    build:
      context: Front
      dockerfile: Dockerfile
    container_name: angular_container
    restart: always
    ports:
      - 4200:4200
      
    #develop:
    #  watch:
    #    - action: rebuild
    #      path: ./Front/.
volumes:
  mysql_data: